site_name: DotFiles
# nav:
#   - None: 'None'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tilde
  - meta
  - toc:
      permalink: '#'

plugins:
  - search
  - macros

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: black
    accent: indigo
  # font:
  # text: https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/ttf/JetBrainsMono-Regular.ttf
  # code: Roboto Mono

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _js/tables.js

extra_css:
  - _css/main.css

use_directory_urls: true

extra:
  test: "this is just for test!"
